<?php 
if(!isset($_SESSION['id'])){
    $title = 'Login';
    $this->headTitle($title);
    $form->setAttribute('action', $this->url('admin', ['action' => 'login']));
    $form->prepare();
?>
<?php if(isset($error)){?>
<div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <?php echo $error;?>
</div>
<?php }?>
<div class="row">
    <div class="col-md-3 hidden-xs"></div>
    <div class="col-md-6 login-page">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
        <?php echo $this->form()->openTag($form);?>
        <div class="form-group">
            <?php echo $this->formRow($form->get('email'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('pwd'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formSubmit($form->get('submit'));?>
        </div>
        <?php echo $this->form()->closeTag();?>
    </div>
    <div class="col-md-3 hidden-xs"></div>
</div>
<style>
    .login-page *{
        text-align:center;
    }
</style>

<script>
    $(document).ready(function(){
        $('.login-page input[type="text"], .login-page input[type="email"], .login-page input[type="password"]').each(function(){
            $(this).addClass('form-control');
        });
        $('.login-page button, .login-page input[type="submit"]').each(function(){
            $(this).addClass('btn btn-default');
        });
    });
</script>

<?php }?>