<?php $this->headTitle($this->escapeHtml($article->title));?>


<div class="row pre-article">
    <div class="col-md-12">
        <img src="http://www.younes-sadmi.fr/personal_projects/investigator/<?php echo $this->escapeHtml($article->url_picture);?>" alt="" class="img-rounded img-responsive article-picture">
    </div>
    <div class="col-md-12">
        <h1><?php echo $this->escapeHtml($article->title);?></h1>
    </div>
    <div class="col-md-12 article-informations">
        <p><?php echo $this->escapeHtml($article->view);?> <i class="fa fa-eye"></i></p>
        <p>
            <span><?php echo $this->escapeHtml(date_format(new DateTime($article->date_publish), 'd/m/Y \à H:i:s')); ?> <i class="fa fa-calendar-o"></i></span>
            <!-- <span>par</span>-->
            <!-- <span><?php echo $this->escapeHtml($article->idadmin); ?></span>-->
        </p>
        <!-- <p><?php echo $this->escapeHtml($article->idcategory); ?></p>-->
    </div>
    <div class="col-md-12">
        <div class="social_network">
            <ul class="share-buttons">
                <li id="fb">
                    <a href="https://www.facebook.com/sharer/sharer.php?u=http://investigator.local<?php echo $this->url('article', ['action'=>'afficher', 'id'=>$article->id]); ?>" title="Partager sur Facebook" target="_blank">
                        <img src="http://02d0bc7cfd78f01a9c97-e4d5bb03d6dfe962539fd332904d9351.r61.cf1.rackcdn.com/wp-content/plugins/simple-share-buttons-adder/buttons/simple/facebook.png">
                    </a>
                </li>
                <li id="twt">
                    <a href="https://twitter.com/intent/tweet?source=http://investigator.local<?php echo $this->url('article', ['action'=>'afficher', 'id'=>$article->id]); ?>via=Investigator" target="_blank" title="Partager sur Tweeter">
                        <img src="http://02d0bc7cfd78f01a9c97-e4d5bb03d6dfe962539fd332904d9351.r61.cf1.rackcdn.com/wp-content/plugins/simple-share-buttons-adder/buttons/simple/twitter.png">
                    </a>
                </li>
                <li id="gplus">
                    <a href="https://plus.google.com/share?url=http://investigator.local<?php echo $this->url('article', ['action'=>'afficher', 'id'=>$article->id]); ?>" target="_blank" title="Partager sur Google+">
                        <img src="http://02d0bc7cfd78f01a9c97-e4d5bb03d6dfe962539fd332904d9351.r61.cf1.rackcdn.com/wp-content/plugins/simple-share-buttons-adder/buttons/simple/google.png">
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-12">
        <hr>
        <article>
            <?php echo $article->content; ?>
        </article>
    </div>
</div>


<style>
    .pre-article{
        position: relative;
    }

    .pre-article .article-picture{
        display: block;
        margin-left: auto;
        margin-right: auto;
    }

    .pre-article .article-informations{
        text-align:right;
    }

    hr {
        border: 0;
        height: 1px;
        background-image: linear-gradient(to right, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.75), rgba(0, 0, 0, 0));
        margin: 20px;
    }



    div.social_network {
        display: block;
        width: 100%;
        /* height: 140px; */
    }
    ul.share-buttons {
        list-style: none;
        padding: 0;
    }
    ul.share-buttons li {
        display: inline;
    }

</style>
<script>
    $(document).ready(function(){
        //pour que l'image ne sortent pas de l'écran mobile
        $('article img').each(function(i, e){
            $(this).addClass('img-responsive');
            //            $(this).css('width', 'auto');
            $(this).css('height', 'auto');
            $(this).css('display', 'block');
            $(this).css('margin-left', 'auto');
            $(this).css('margin-right', 'auto');

        });
    });
</script>