<?php $this->headTitle('Home');?>

<div class="row articles-preview">
    <?php foreach($articles as $article){?>
    <div class="col-md-12 row article-preview">
        <div class="col-md-3">
            <a href="<?php echo $this->url('article', ['action'=>'afficher', 'id'=>$article->id]); ?>">
                <img src="http://www.younes-sadmi.fr/personal_projects/investigator/<?php echo $this->escapeHtml($article->url_picture);?>" alt="" class="article-picture img-rounded img-responsive">
            </a>
        </div>
        <div class="col-md-9">
            <a href="<?php echo $this->url('article', ['action'=>'afficher', 'id'=>$article->id]); ?>">
                <p class="date_publish"><i class="fa fa-calendar-o"></i> <?php echo $this->escapeHtml(date_format(new DateTime($article->date_publish), 'd-m-Y'));?></p>
                <p class="title"><?php echo $this->escapeHtml($article->title);?></p>
                <p class="description"><?php echo $this->escapeHtml($article->description);?></p>
                <p class="view"><?php echo $this->escapeHtml($article->view);?> <i class="fa fa-eye"></i></p>
                <!--            <p class="idcategory"><?php echo $this->escapeHtml($article->idcategory);?></p>-->
            </a>
        </div>
    </div>
    <?php } ?>
</div>


<style>
    .articles-preview a {
        color: inherit;
    }

    .articles-preview .article-preview{
        display:block;
        position: relative;
        border-bottom: solid 1px #eee;
        padding: 10px;
    }

    .articles-preview .article-preview img.article-picture{
        width: 70%;
        display: block;
        margin-left:auto;
        margin-right:auto;
    }
    @media (max-width: 992px){
        .articles-preview .article-preview img.article-picture{
            max-width: 40%;
        }
    }

    .articles-preview .article-preview .title{
        font-size: 22px;
        font-weight: bold;
    }

    .articles-preview .article-preview .description{
        font-size: 14px;
    }

    .articles-preview .article-preview .view{
        position: absolute;
        bottom: 0px;
        right: 10px;
    }

    .articles-preview .article-preview .date_publish{
        color: #aaa;
        position: absolute;
        top: 0px;
        right: 10px;

    }

    .articles-preview .article-preview .idcategory{

    }
</style>